#pragma once

#include "util.h"

#define OPENSSL_API_COMPAT 0x10101000L
#define OPENSSL_NO_DEPRECATED 1

#define LUNARSSL_ERR_REASON (ERR_reason_error_string(ERR_get_error()))

enum LUNARSSL_VERSION_TYPE {
    LUNARSSL_VERSION_TEXT_SHORT,
    LUNARSSL_VERSION_TEXT_LONG,
    LUNARSSL_VERSION_TEXT_FULL,
    LUNARSSL_VERSION_COMPILER,
    LUNARSSL_VERSION_BUILT_ON,
    LUNARSSL_VERSION_PLATFORM,
    LUNARSSL_VERSION_OPENSSLDIR,
    LUNARSSL_VERSION_ENGINESDIR,
    LUNARSSL_VERSION_MODULESDIR,
    LUNARSSL_VERSION_CPUINFO,
    LUNARSSL_VERSION_WINCTX,
};

#define LUNARSSL_VERSION_MAP(XX)                                        \
    XX(LUNARSSL_VERSION_TEXT_SHORT, OPENSSL_VERSION_STRING, "short")    \
    XX(LUNARSSL_VERSION_TEXT_LONG, OPENSSL_FULL_VERSION_STRING, "long") \
    XX(LUNARSSL_VERSION_TEXT_FULL, OPENSSL_VERSION, "full")             \
    XX(LUNARSSL_VERSION_COMPILER, OPENSSL_CFLAGS, "compiler")           \
    XX(LUNARSSL_VERSION_BUILT_ON, OPENSSL_BUILT_ON, "built_on")         \
    XX(LUNARSSL_VERSION_PLATFORM, OPENSSL_PLATFORM, "platform")         \
    XX(LUNARSSL_VERSION_OPENSSLDIR, OPENSSL_DIR, "openssldir")          \
    XX(LUNARSSL_VERSION_ENGINESDIR, OPENSSL_ENGINES_DIR, "enginesdir")  \
    XX(LUNARSSL_VERSION_MODULESDIR, OPENSSL_MODULES_DIR, "modulesdir")  \
    XX(LUNARSSL_VERSION_CPUINFO, OPENSSL_CPU_INFO, "cpuinfo")           \
    XX(LUNARSSL_VERSION_WINCTX, OPENSSL_WINCTX, "winctx")

enum LUNARSSL_INFO_TYPE {
    LUNARSSL_INFO_OPENSSLDIR,
    LUNARSSL_INFO_ENGINESDIR,
    LUNARSSL_INFO_MODULESDIR,
    LUNARSSL_INFO_DSO_EXTENSION,
    LUNARSSL_INFO_FILE_SEPARATOR,
    LUNARSSL_INFO_LIST_SEPARATOR,
    LUNARSSL_INFO_SEED_SOURCE,
    LUNARSSL_INFO_CPU_SETTINGS,
    LUNARSSL_INFO_WINCTX,
};

#define LUNARSSL_INFO_MAP(XX)                                                               \
    XX(LUNARSSL_INFO_OPENSSLDIR, OPENSSL_INFO_CONFIG_DIR, "openssldir")                     \
    XX(LUNARSSL_INFO_ENGINESDIR, OPENSSL_INFO_ENGINES_DIR, "enginesdir")                    \
    XX(LUNARSSL_INFO_MODULESDIR, OPENSSL_INFO_MODULES_DIR, "modulesdir")                    \
    XX(LUNARSSL_INFO_DSO_EXTENSION, OPENSSL_INFO_DSO_EXTENSION, "dso_extension")            \
    XX(LUNARSSL_INFO_FILE_SEPARATOR, OPENSSL_INFO_DIR_FILENAME_SEPARATOR, "file_separator") \
    XX(LUNARSSL_INFO_LIST_SEPARATOR, OPENSSL_INFO_LIST_SEPARATOR, "list_separator")         \
    XX(LUNARSSL_INFO_SEED_SOURCE, OPENSSL_INFO_SEED_SOURCE, "seed_source")                  \
    XX(LUNARSSL_INFO_CPU_SETTINGS, OPENSSL_INFO_CPU_SETTINGS, "cpuinfo")                    \
    XX(LUNARSSL_INFO_WINCTX, OPENSSL_INFO_WINDOWS_CONTEXT, "winctx")
